apiVersion: apps/v1
kind: Deployment
metadata:
  name: "tomcat-deployment"
  labels:
    app: "vproapp"
spec:
  selector:
    matchLabels:
      app: "vproapp"
  replicas: 1
  template:
    spec:
       metadata:
         labels:
           app: "vproapp"
       containers:
          - name: vproapp
            image: haarubabe/tomcat:V2
            ports:
              - containerPort: 8080
       initContainers:
          - name: init-db
            image: busybox
            command: ["sh","-c","until nslookup vprodb; do sleep 2; done;"]
          - name: init-memcache
            image: busybox
            command: ["sh","-c","until nslookup vprocache01; do sleep 2; done;"]